### ISSUE TITLE
能否创建共享agent id，与多个用户共享控制

### ISSUE THREAD

**Issue by WMMMD** [hack-fan/serverfan#1]

**Comment by hyacinthus** [comment]
谢谢提建议，这个问题在云服务的版本未来会支持，开源自部署版本不会支持共享类的功能。

在云服务里，其实 skadi 中的 UserID 是一个组织，用户还有一层，将来组织内是可以共享 Agent 的。

总之在计划中，但还没有时间表。

**Comment by WMMMD** [comment]
> 谢谢提建议，这个问题在云服务的版本未来会支持，开源自部署版本不会支持共享类的功能。
> 
> 在云服务里，其实 skadi 中的 UserID 是一个组织，用户还有一层，将来组织内是可以共享 Agent 的。
> 
> 总之在计划中，但还没有时间表。

好的 感谢～
