### ISSUE TITLE
每天 100 条消息太少了，是否有付费版？

### ISSUE THREAD

**Issue by m2acgi** [hack-fan/serverfan#3]
如题，谢谢

**Comment by hyacinthus** [comment]
微信公众号版本，是为了让大家方便，不用装额外的聊天 App ，这个条数限制继承自微信的一些规则，即使有付费版也不会取消的。所以只能用在提醒数量比较少的场景。

提醒数量比较多的情况，只能用 企业微信，tg，slack，飞书之类团队协作聊天软件。项目后续会支持。你也可以找找，有很多类似的项目。
