### ISSUE TITLE
不支持换行符了？

### ISSUE THREAD

**Issue by tantalate** [hack-fan/serverfan#6]
之前可以添加换行符，而且消息内容可以比较长，现在只能显示十几个字，也不能换行了，后面的只有...了

**Comment by hyacinthus** [comment]
微信的模版消息通用调整吧…没什么办法，我有空增加点别的 im 支持

tantalate ***@***.***> 于 2023年10月24日周二 下午4:36写道：

**Comment by tantalate** [comment]
谢谢，如果模板消息增加一个URL，点进去能看到完整消息也挺方便的
